// Static catalogue of common road/gravel bike parts, grouped into categories.
// Users can add custom parts that get persisted per bike in IndexedDB.

export const PARTS_CATALOGUE = [
  {
    category: "Frame & Structure",
    parts: [
      "Frame",
      "Fork",
      "Head tube",
      "Top tube",
      "Down tube",
      "Seat tube",
      "Chainstays",
      "Seatstays",
      "Bottom bracket shell",
      "Dropouts",
      "Rear derailleur hanger",
    ],
  },
  {
    category: "Cockpit",
    parts: [
      "Handlebars",
      "Stem",
      "Headset",
      "Bar tape",
      "Spacers",
      "Saddle",
      "Seatpost",
      "Seatpost clamp",
    ],
  },
  {
    category: "Drivetrain",
    parts: [
      "Crankset",
      "Crank arms",
      "Chainrings",
      "Bottom bracket",
      "Pedals",
      "Cleats",
      "Chain",
      "Cassette",
      "Freehub body",
      "Front derailleur",
      "Rear derailleur",
      "Gear shifters / brake levers",
      "Shift cables / electronic wires",
      "Cable housing",
    ],
  },
  {
    category: "Braking System",
    parts: [
      "Disc brake rotors",
      "Brake calipers",
      "Brake pads",
      "Hydraulic hoses / brake cables",
      "Brake fluid reservoir",
    ],
  },
  {
    category: "Wheels",
    parts: [
      "Front tyre",
      "Rear tyre",
      "Front wheel",
      "Rear wheel",
      "Rims",
      "Hubs",
      "Spokes",
      "Nipples",
      "Axles",
      "Quick release skewers",
      "Thru-axles",
      "Inner tubes",
      "Tubeless valves",
      "Tubeless sealant",
      "Rim tape",
    ],
  },
  {
    category: "Bearings & Rotating Parts",
    parts: [
      "Headset bearings",
      "Bottom bracket bearings",
      "Hub bearings",
      "Pulley wheels / jockey wheels",
    ],
  },
  {
    category: "Gravel-Specific Extras",
    parts: [
      "Frame bags",
      "Top tube bag",
      "Handlebar bag",
      "Mudguards / fenders",
      "Bikepacking mounts",
      "Extra bottle cages",
      "Dropper seatpost",
      "Chain guide",
    ],
  },
  {
    category: "Accessories & Electronics",
    parts: [
      "Cycling computer mount",
      "Bike computer",
      "Power meter",
      "Speed sensor",
      "Cadence sensor",
      "Heart rate monitor",
      "Front light",
      "Rear light",
      "Radar light",
      "Bell",
      "GPS tracker",
    ],
  },
  {
    category: "Fasteners & Small Parts",
    parts: [
      "Bolts",
      "Compression plug / star nut",
      "Cable end caps",
      "Valve caps",
      "Derailleur pulleys",
      "Brake pad retaining pins",
      "Chain quick link",
    ],
  },
];

export const MAINTENANCE_ACTIONS = [
  "Installed",
  "Replaced",
  "Serviced",
  "Cleaned",
  "Lubed",
  "Adjusted",
  "Inspected",
  "Note",
];
